# Generated by Django 3.1.1 on 2023-01-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='author_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_phno',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_semester',
            field=models.IntegerField(default=None),
        ),
    ]
