# Generated by Django 3.1.1 on 2023-01-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0004_auto_20230118_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_password',
        ),
    ]
