# Generated by Django 3.1.1 on 2023-01-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0005_remove_student_stud_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
