# Generated by Django 3.1.1 on 2023-01-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0007_auto_20230119_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_password',
        ),
    ]
