# Generated by Django 3.1.1 on 2023-01-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0009_student_stud_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_password',
            field=models.CharField(default='1234', max_length=50, null=True),
        ),
    ]
